### ISSUE TITLE
It doesn't work on PaperSpigot_1.15.2_b143

### ISSUE THREAD

**Issue by xslingcn** [BananaPuncher714/RadioBoard#4]
> org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[Paper-1.15.2-b143.jar:git-Paper-142]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435) ~[Paper-1.15.2-b143.jar:git-Paper-142]
>         at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[Paper-1.15.2-b143.jar:git-Paper-142]
>         at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[Paper-1.15.2-b143.jar:git-Paper-142]
>         at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[Paper-1.15.2-b143.jar:git-Paper-142]
>         at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[Paper-1.15.2-b143.jar:git-Paper-142]
>         at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[Paper-1.15.2-b143.jar:git-Paper-142]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
> Caused by: java.lang.IllegalStateException: Unable to find method null ([class net.minecraft.server.v1_15_R1.ServerConnection]).
>         at io.github.bananapuncher714.radioboard.tinyprotocol.Reflection.getTypedMethod(Reflection.java:242) ~[?:?]
>         at io.github.bananapuncher714.radioboard.tinyprotocol.Reflection.getMethod(Reflection.java:203) ~[?:?]
>         at io.github.bananapuncher714.radioboard.tinyprotocol.Reflection.getTypedMethod(Reflection.java:240) ~[?:?]
>         at io.github.bananapuncher714.radioboard.tinyprotocol.TinyProtocol.<clinit>(TinyProtocol.java:59) ~[?:?]
>         ... 10 more

..and here's my java info

> [root@localhost ~]# java -version
> openjdk version "1.8.0_242"
> OpenJDK Runtime Environment (build 1.8.0_242-b08)
> OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

**Comment by BananaPuncher714** [comment]
I'm looking into the problem, it seems to be an issue with the recent builds of Paper.

**Comment by BananaPuncher714** [comment]
This should be fixed with v1.4.2 Please re-open if this error still persists.
