### ISSUE TITLE
Can't connect to X11 window server using 'localhost:11.0' as the value of the DISPLAY variable.

### ISSUE THREAD

**Issue by MrTangsr** [BananaPuncher714/RadioBoard#7]
This error occurred when I start my 1.15.2 paper server with RadioBoard v1.4.2. Do you know how this happened? here is my log.
[latest.log](https://github.com/BananaPuncher714/RadioBoard/files/4669257/latest.log)

**Comment by BananaPuncher714** [comment]
You may need to specify `-Djava.awt.headless=true` parameter at startup time. Has RadioBoard worked properly for you before, or has this error always occurred?

**Comment by MrTangsr** [comment]
I add that parameter. It works. thank you so much! RadioBoard worked properly before. But one day the error occurred after a server restart.
